Repository club-soda/club-soda-guide, pull requests merged in 2018-12, with the labels that each got.

#185 search drinks
  assets/brunch-config.js
  assets/elm/DrinkCard.elm
  assets/elm/Search.elm
  assets/elm/SearchDrink.elm
  assets/elm/SearchVenue.elm
  assets/js/search.js
  mix.lock
Labels: awaiting-review

#168 Admin password
  README.md
  lib/cs_guide/accounts/user.ex
  lib/cs_guide/auth.ex
  lib/cs_guide_web/controllers/admin_controller.ex
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/session_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/plugs/auth.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/admin/index.html.eex
  lib/cs_guide_web/templates/session/new.html.eex
  lib/cs_guide_web/templates/venue/show.html.eex
  lib/cs_guide_web/views/admin_view.ex
  lib/cs_guide_web/views/session_view.ex
  priv/repo/migrations/20181203115146_add_password.exs
  test/cs_guide/accounts/accounts_test.exs
  test/cs_guide_web/controllers/auth_controller_test.exs
  test/cs_guide_web/controllers/brand_controller_test.exs
  test/cs_guide_web/controllers/drink_controller_test.exs
  test/cs_guide_web/controllers/drink_style_controller_test.exs
  test/cs_guide_web/controllers/user_controller_test.exs
  test/cs_guide_web/controllers/venue_controller_test.exs
  test/cs_guide_web/controllers/venue_types_controller_test.exs
  test/support/setup_helpers.ex
Labels: in-review

#190 Readme amends #189
  README.md
Labels: awaiting-review

#193 #192 Removes unneeded IO.inspect in seeds
  priv/repo/seeds.exs
Labels: awaiting-review

#191 Allow multiples of 0.01 in abv input
  mix.exs
Labels: awaiting-review

#195 Search Styling #130 #44
  assets/css/app.css
  assets/elm/Search.elm
  assets/elm/SearchDrink.elm
  assets/elm/SearchVenue.elm
Labels: awaiting-review

#200 Image documentation
  README.md
Labels: awaiting-review

#198 Adds drink style to drink cards #106
  assets/elm/DrinkCard.elm
  assets/elm/DrinksCarousel.elm
  assets/elm/SearchDrink.elm
  assets/elm/SharedTypes.elm
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/drink_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/templates/components/drink_card.html.eex
Labels: awaiting-review

#199 fixes venue/edit links
  lib/cs_guide_web/templates/venue/show.html.eex
Labels: awaiting-review

#201 #40 Updates ABV dropdown values
  assets/elm/SearchDrink.elm
Labels: awaiting-review

#202 #182 Removes external image code for venues
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/controllers/search_venue_controller.ex
  lib/cs_guide_web/templates/components/venue_card.html.eex
  lib/cs_guide_web/templates/user/new.html.eex
  lib/cs_guide_web/templates/venue/edit.html.eex
  lib/cs_guide_web/templates/venue/new.html.eex
  lib/cs_guide_web/templates/venue/show.html.eex
  priv/repo/migrations/20181205155845_drop_external_venue_img_column.exs
  priv/repo/seeds.exs
Labels: awaiting-review

#203 Creates mobile burger menu #194
  assets/css/app.css
  assets/elm/SearchDrink.elm
  assets/elm/SearchVenue.elm
  assets/static/images/burger_menu.svg
  assets/static/images/close_menu_x.svg
  lib/cs_guide_web/templates/layout/app.html.eex
Labels: awaiting-review

#205 #204 Replaces venue placeholder image
  assets/css/app.css
  assets/elm/SearchVenue.elm
  lib/cs_guide_web/templates/venue/show.html.eex
Labels: awaiting-review

#206 Search documentation
  README.md
Labels: awaiting-review

#209 Sort venues score/name
  lib/cs_guide_web/controllers/search_venue_controller.ex
  mix.lock
Labels: awaiting-review

#208 updates alog to 0.3
  lib/cs_guide/accounts/user.ex
  lib/cs_guide/categories/drink_style.ex
  lib/cs_guide/resources/drink.ex
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/drink_controller.ex
  lib/cs_guide_web/controllers/drink_style_controller.ex
  lib/cs_guide_web/controllers/drink_type_controller.ex
  lib/cs_guide_web/controllers/signup_controller.ex
  lib/cs_guide_web/controllers/user_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/controllers/venue_type_controller.ex
  lib/cs_guide_web/templates/user/new.html.eex
  lib/cs_guide_web/templates/venue/edit.html.eex
  lib/cs_guide_web/templates/venue/new.html.eex
  mix.exs
  mix.lock
  priv/repo/migrations/20181207100619_link_venues_users.exs
  test/cs_guide/accounts/accounts_test.exs
  test/cs_guide/categories/categories_test.exs
  test/cs_guide/resources/resources_test.exs
  test/cs_guide_web/controllers/auth_controller_test.exs
  test/cs_guide_web/controllers/brand_controller_test.exs
  test/cs_guide_web/controllers/drink_controller_test.exs
  test/cs_guide_web/controllers/drink_style_controller_test.exs
  test/cs_guide_web/controllers/page_controller_test.exs
  test/cs_guide_web/controllers/search_venue_controller_test.exs
  test/cs_guide_web/controllers/user_controller_test.exs
  test/cs_guide_web/controllers/venue_controller_test.exs
  test/cs_guide_web/controllers/venue_types_controller_test.exs
  test/support/setup_helpers.ex
Labels: awaiting-review

#224 #8 Mends drinks carousel
  assets/elm/DrinksCarousel.elm
  lib/cs_guide_web/controllers/drink_controller.ex
Labels: awaiting-review

#225 #49 Updates Retailer pages
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/controllers/retailer_controller.ex
  lib/cs_guide_web/templates/retailer/edit.html.eex
  lib/cs_guide_web/templates/retailer/new.html.eex
  test/cs_guide_web/controllers/retailer_controller_test.exs
Labels: awaiting-review

#229 Prevent duplicate emails being added to database
  lib/cs_guide/accounts/user.ex
  mix.exs
  mix.lock
  test/cs_guide/accounts/accounts_test.exs
Labels: awaiting-review

#210 add elm-criteria for filtering
  assets/css/app.css
  assets/elm.json
  assets/elm/Search.elm
  assets/elm/SearchDrink.elm
  assets/elm/TypeAndStyle.elm
Labels: awaiting-review

#238 Use brand name in url
  assets/elm/DrinkCard.elm
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/brand/add_photo.html.eex
  lib/cs_guide_web/templates/brand/edit.html.eex
  lib/cs_guide_web/templates/brand/index.html.eex
  lib/cs_guide_web/templates/brand/show.html.eex
  lib/cs_guide_web/templates/components/drink_card.html.eex
  mix.exs
  mix.lock
  priv/repo/migrations/20181213132542_lower_index.exs
  test/cs_guide_web/controllers/brand_controller_test.exs
Labels: awaiting-review

#226 Search drinks venues
  assets/brunch-config.js
  assets/elm/Search.elm
  assets/elm/SearchAll.elm
  assets/elm/SearchDrink.elm
  assets/elm/SearchVenue.elm
  assets/elm/SharedTypes.elm
  assets/js/search.js
  lib/cs_guide/resources/drink.ex
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/controllers/search_all_controller.ex
  lib/cs_guide_web/controllers/search_drink_controller.ex
  lib/cs_guide_web/controllers/search_venue_controller.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/page/index.html.eex
  lib/cs_guide_web/templates/search_all/index.html.eex
  lib/cs_guide_web/templates/search_drink/index.html.eex
  lib/cs_guide_web/views/search_all_view.ex
  test/cs_guide_web/controllers/search_all_controller_test.exs
Labels: awaiting-review

#241 allow venue owner to edit venue
  lib/cs_guide/auth.ex
  lib/cs_guide_web/controllers/signup_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/plugs/auth.ex
  lib/cs_guide_web/router.ex
Labels: awaiting-review

#244 removes brand edit links for non admins
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/templates/brand/show.html.eex
Labels: awaiting-review

#249 remove STYLE from drink card #219
  lib/cs_guide_web/templates/components/drink_card.html.eex
Labels: awaiting-review

#248 Search styling #133 #135
  assets/css/app.css
  assets/elm/Search.elm
  assets/elm/SearchAll.elm
  lib/cs_guide_web/templates/page/index.html.eex
Labels: awaiting-review

#265 #214 Adds brands into drinks searches
  assets/elm/SharedTypes.elm
Labels: awaiting-review

#266 Abv required
  lib/cs_guide/resources/drink.ex
  lib/cs_guide_web/templates/drink/new.html.eex
  test/cs_guide_web/controllers/drink_controller_test.exs
Labels: awaiting-review

#268 #13 Joinclubsoda opens in new tab
  README.md
  lib/cs_guide/resources/brand.ex
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/templates/page/index.html.eex
  mix.exs
  mix.lock
  test/cs_guide/resources/resources_test.exs
  test/cs_guide_web/controllers/brand_controller_test.exs
Labels: awaiting-review

#243 #14 Sets up static page templates and schema
  README.md
  assets/css/app.css
  assets/static/images/circle-logo.svg
  lib/cs_guide/static_pages/static_pages.ex
  lib/cs_guide_web/controllers/page_controller.ex
  lib/cs_guide_web/controllers/static_page_controller.ex
  lib/cs_guide_web/plugs/static_pages.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/layout/app.html.eex
  lib/cs_guide_web/templates/retailer/index.html.eex
  lib/cs_guide_web/templates/static_page/edit.html.eex
  lib/cs_guide_web/templates/static_page/index.html.eex
  lib/cs_guide_web/templates/static_page/new.html.eex
  lib/cs_guide_web/templates/static_page/show.html.eex
  lib/cs_guide_web/views/static_page_view.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20181214101549_create_static_pages.exs
  test/cs_guide_web/controllers/static_page_controller_test.exs
Labels: awaiting-review

#267 Venue page map
  assets/css/app.css
  lib/cs_guide_web/templates/venue/address_under_map.html.eex
  lib/cs_guide_web/templates/venue/info.html.eex
  lib/cs_guide_web/templates/venue/link_under_map.html.eex
  lib/cs_guide_web/templates/venue/show.html.eex
  lib/cs_guide_web/views/venue_view.ex
Labels: awaiting-review

#269 adds api key as variable #197
  config/config.exs
  lib/cs_guide_web/templates/venue/show.html.eex
Labels: awaiting-review

#272 #49 #14 Adds static pages and retailers to admin dashboard
  lib/cs_guide_web/templates/admin/index.html.eex
  test/cs_guide_web/controllers/venue_controller_test.exs
Labels: awaiting-review

#273 #262 Replaces CS logo asset in footer
  assets/static/images/circle-logo.svg
  assets/static/images/cs-logo.png
  lib/cs_guide_web/templates/layout/app.html.eex
Labels: awaiting-review

#275 #260 Adds Google Analytics script
  lib/cs_guide_web/templates/layout/app.html.eex
Labels: awaiting-review

#278 #236 Updates z-indexes so burger menu is on top of filters
  assets/elm/SearchDrink.elm
  lib/cs_guide_web/templates/layout/app.html.eex
  lib/cs_guide_web/templates/venue/info.html.eex
Labels: awaiting-review

#282 #61 Writes script to update CS score
  priv/repo/update_cs_score.exs
Labels: awaiting-review

#283 update autoform version
  mix.exs
  mix.lock
Labels: in-progress

#284 update autoform
  mix.exs
  mix.lock
Labels: awaiting-review
