Repository club-soda/club-soda-guide, pull requests merged in 2019-02, with the labels that each got.

#440 Filter venue type list
  lib/cs_guide_web/controllers/search_venue_controller.ex
Labels: awaiting-review

#439 toggle drink card
  lib/cs_guide_web/templates/components/drink_card.html.eex
Labels: awaiting-review

#441 Hide title for empty section
  lib/cs_guide_web/templates/brand/show.html.eex
  lib/cs_guide_web/views/brand_view.ex
  test/cs_guide_web/views/brand_view_test.exs
Labels: awaiting-review

#447 use elm-criteria dropdowns
  assets/elm.json
  assets/elm/Abv.elm
  assets/elm/SearchDrink.elm
  assets/elm/SearchVenue.elm
  assets/elm/VenueScore.elm
  assets/elm/VenueType.elm
  assets/js/search.js
Labels: awaiting-review

#449 #351 Changes detail on twitter svg so name is updated on github
  assets/static/images/Twitter.svg
Labels: awaiting-review

#448 use udpated_at instead of inserted_at for sorting
  lib/cs_guide/categories/drink_style.ex
  lib/cs_guide/categories/drink_type.ex
  lib/cs_guide/resources/brand.ex
  lib/cs_guide/resources/drink.ex
  lib/cs_guide/resources/resources.ex
  lib/cs_guide/resources/venue.ex
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/csv_controller.ex
  lib/cs_guide_web/controllers/discount_code_controller.ex
  lib/cs_guide_web/controllers/retailer_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/controllers/wholesaler_controller.ex
  lib/cs_guide_web/plugs/auth.ex
  lib/cs_guide_web/views/brand_view.ex
  lib/cs_guide_web/views/discount_code_view.ex
  lib/cs_guide_web/views/drink_style_view.ex
  lib/cs_guide_web/views/drink_view.ex
  lib/cs_guide_web/views/retailer_view.ex
  lib/cs_guide_web/views/static_page_view.ex
  lib/cs_guide_web/views/user_view.ex
  lib/cs_guide_web/views/venue_view.ex
  lib/cs_guide_web/views/wholesaler_view.ex
  mix.exs
  mix.lock
  priv/repo/update_cs_score.exs
Labels: awaiting-review

#455 allow hyphen in brand name
  assets/elm/DrinkCard.elm
  lib/cs_guide_web/controllers/brand_controller.ex
Labels: awaiting-review

#457 format brand name for url
  lib/cs_guide_web/templates/components/drink_card.html.eex
  lib/cs_guide_web/views/components_view.ex
Labels: awaiting-review

#461 use alog all function for discount code
  lib/cs_guide_web/controllers/discount_code_controller.ex
Labels: awaiting-review

#462 #451 Discount code changes
  README.md
  lib/cs_guide_web/controllers/discount_code_controller.ex
  lib/cs_guide_web/templates/discount_code/new.html.eex
  lib/cs_guide_web/templates/retailer/index.html.eex
  lib/cs_guide_web/views/brand_view.ex
  test/cs_guide_web/views/brand_view_test.exs
Labels: awaiting-review

#463 add slug to brand
  assets/elm/DrinkCard.elm
  assets/elm/DrinksCarousel.elm
  assets/elm/SharedTypes.elm
  lib/cs_guide/resources/brand.ex
  lib/cs_guide/resources/drink.ex
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/drink_controller.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/brand/edit.html.eex
  lib/cs_guide_web/templates/brand/index.html.eex
  lib/cs_guide_web/templates/brand/new.html.eex
  lib/cs_guide_web/templates/brand/show.html.eex
  lib/cs_guide_web/templates/components/drink_card.html.eex
  lib/cs_guide_web/views/components_view.ex
  priv/repo/add_brand_slug.exs
  priv/repo/migrations/20190208124459_brand_slug.exs
  test/cs_guide_web/controllers/brand_controller_test.exs
Labels: awaiting-review

#464 #446 Adds padding for landing title on mobile
  lib/cs_guide_web/templates/page/index.html.eex
Labels: awaiting-review

#467 #460 Displays new lines as new lines using <br/>
  lib/cs_guide_web/templates/venue/info.html.eex
  lib/cs_guide_web/views/venue_view.ex
  test/cs_guide_web/controllers/venue_controller_test.exs
Labels: awaiting-review

#469 Small update in wording of company or chain venue field
  lib/cs_guide_web/templates/user/new.html.eex
  lib/cs_guide_web/templates/venue/edit.html.eex
  lib/cs_guide_web/templates/venue/new.html.eex
Labels: awaiting-review

#470 Adds colon after "Retailer" sub-title in discount code admin screens
  lib/cs_guide_web/templates/discount_code/edit.html.eex
  lib/cs_guide_web/templates/discount_code/new.html.eex
Labels: question

#454 #58 #28 Venue image upload and image carousel
  assets/brunch-config.js
  assets/css/app.css
  assets/elm/DrinksCarousel.elm
  assets/elm/SharedTypes.elm
  assets/elm/VenueCarousel.elm
  assets/js/carousel-swipe.js
  assets/static/images/left-chevron.svg
  assets/static/images/right-chevron.svg
  config/config.exs
  config/test.exs
  lib/cs_guide/images/venue_image.ex
  lib/cs_guide/resources/resources.ex
  lib/cs_guide_web/controllers/brand_controller.ex
  lib/cs_guide_web/controllers/page_controller.ex
  lib/cs_guide_web/controllers/search_all_controller.ex
  lib/cs_guide_web/controllers/search_venue_controller.ex
  lib/cs_guide_web/controllers/venue_controller.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/brand/add_cover_photo.html.eex
  lib/cs_guide_web/templates/components/venue_image_upload.html.eex
  lib/cs_guide_web/templates/venue/add_photo.html.eex
  lib/cs_guide_web/templates/venue/info.html.eex
  lib/cs_guide_web/templates/venue/show.html.eex
  priv/repo/migrations/20190204164312_add_photo_no_to_venue_images.exs
  test/cs_guide_web/controllers/venue_controller_test.exs
  test/support/bad-file.jpg
  test/support/good-file.jpg
  test/support/mock_ex_aws.ex
Labels: awaiting-review

#466 #459 Drink card styling tweaks
  assets/css/app.css
  assets/elm/DrinkCard.elm
  assets/elm/SearchDrink.elm
  lib/cs_guide_web/templates/components/cocktail_card.html.eex
  lib/cs_guide_web/templates/components/drink_card.html.eex
  lib/cs_guide_web/templates/venue/show.html.eex
Labels: awaiting-review

#474 #468 Updates documentation on brand membership
  README.md
Labels: awaiting-review

#475 update script for social links
  priv/repo/change_social_media_handles_to_urls.ex
Labels: awaiting-review

#476 #471 Styles links on admin to be buttons
  lib/cs_guide_web/templates/admin/index.html.eex
Labels: awaiting-review

#479 #121 Creates fn to shuffle drinks by weighting
  lib/cs_guide_web/controllers/drink_controller.ex
  test/cs_guide_web/controllers/drink_controller_test.exs
Labels: awaiting-review

#480 toggle drink card on mobile
  assets/elm/DrinksCarousel.elm
Labels: awaiting-review

#482 slug upload image brand
  lib/cs_guide_web/templates/brand/add_cover_photo.html.eex
  lib/cs_guide_web/templates/brand/add_photo.html.eex
  lib/cs_guide_web/templates/components/image_upload.html.eex
Labels: awaiting-review

#485 #131 Creates sponsor html for landing page
  README.md
  lib/cs_guide/sponsor.ex
  lib/cs_guide_web/controllers/page_controller.ex
  lib/cs_guide_web/controllers/sponsor_controller.ex
  lib/cs_guide_web/router.ex
  lib/cs_guide_web/templates/admin/index.html.eex
  lib/cs_guide_web/templates/page/index.html.eex
  lib/cs_guide_web/templates/sponsor/edit.html.eex
  lib/cs_guide_web/templates/sponsor/index.html.eex
  lib/cs_guide_web/templates/sponsor/new.html.eex
  lib/cs_guide_web/views/sponsor_view.ex
  priv/repo/migrations/20190212160430_creates_sponsor_table.exs
  test/cs_guide_web/controllers/sponsor_controller_test.exs
Labels: awaiting-review

#486 #471 Swaps styling of admin btns and links
  lib/cs_guide_web/templates/admin/index.html.eex
Labels: awaiting-review

#484 add drink carousel on mobile
  assets/css/app.css
  assets/elm/DrinksCarousel.elm
Labels: awaiting-review

#489 #451 Updates docs on single discount codes
  README.md
Labels: awaiting-review

#491 #487 Only shows 'Find One Near Me' btn if venues exist for brand
  lib/cs_guide_web/templates/brand/show.html.eex
  lib/cs_guide_web/views/brand_view.ex
  test/cs_guide_web/views/brand_view_test.exs
Labels: in-review

#492 #490 Tweaks 'Venue listing' copy to avoid nominations
  lib/cs_guide_web/templates/user/new.html.eex
  test/cs_guide_web/controllers/user_controller_test.exs
Labels: awaiting-review

#493 hide scrollbar on drink card
  assets/css/app.css
  assets/elm/DrinkCard.elm
  lib/cs_guide_web/templates/components/drink_card.html.eex
Labels: awaiting-review

#494 #483 Reorder brand pg sections, add see more btn for venues
  assets/css/app.css
  lib/cs_guide_web/templates/brand/show.html.eex
  lib/cs_guide_web/views/brand_view.ex
  test/cs_guide_web/views/brand_view_test.exs
Labels: awaiting-review
